services:
    potogan.rest.client:
        class: Potogan\REST\Client
        factory: [ '@potogan.rest.client_factory', 'build' ]
        public: true
        arguments:
            - https://example.com

    potogan.rest.client_factory:
        class: Potogan\REST\ClientFactory
        arguments:
            - '@potogan.rest.request_factory'
            - '@potogan.rest.transformer'
            - '@potogan.rest.http_client'
        tags:
            - { name: potogan.rest.chain, tag: potogan.rest.middleware, method: addMiddleware }

    potogan.rest.request_factory:
        alias: Provide any RequestFactory implementation as defined in php-http/message-factory

    potogan.rest.stream_factory:
        alias: Provide any StreamFactory implementation as defined in php-http/message-factory

    potogan.rest.http_client:
        alias: Provide any php-http/client-implementation

    potogan.rest.annotation_reader:
        alias: annotation_reader

    potogan.rest.http.uri_merger:
        class: Potogan\REST\Http\UriMerger

    potogan.rest.transformer:
        alias: potogan.rest.transformer.chain

    potogan.rest.transformer.chain:
        class: Potogan\REST\Transformer\Chain
        tags:
            - { name: potogan.rest.chain, tag: potogan.rest.transformer, method: addTransformer }

    potogan.rest.transformer.json:
        class: Potogan\REST\Transformer\Json
        tags:
            - { name: potogan.rest.transformer }

    potogan.rest.transformer.stream:
        class: Potogan\REST\Transformer\Stream
        arguments:
            - '@potogan.rest.stream_factory'
        tags:
            - { name: potogan.rest.transformer }

    potogan.rest.middleware.annotation_reader:
        class: Potogan\REST\Middleware\AnnotationReader
        arguments:
            - '@potogan.rest.annotation_reader'
            - '@potogan.rest.http.uri_merger'
        tags:
            - { name: potogan.rest.middleware }

    potogan.rest.middleware.aware_request:
        class: Potogan\REST\Middleware\AwareRequest
        arguments:
            - '@potogan.rest.http.uri_merger'
        tags:
            - { name: potogan.rest.middleware }

    potogan.rest.middleware.body_provider:
        class: Potogan\REST\Middleware\BodyProvider
        arguments:
            - '@potogan.rest.body_provider'
            - '@potogan.rest.transformer'
        tags:
            - { name: potogan.rest.middleware }

    potogan.rest.body_provider:
        alias: potogan.rest.body_provider.chain

    potogan.rest.body_provider.chain:
        class: Potogan\REST\BodyProvider\Chain
        tags:
            - { name: potogan.rest.chain, tag: potogan.rest.body_provider, method: addProvider }

    potogan.rest.body_provider.aware_request:
        class: Potogan\REST\BodyProvider\AwareRequest
        tags:
            - { name: potogan.rest.body_provider }
